# Generated by Django 5.1.1 on 2024-09-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0005_player_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='b_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
