# Generated by Django 5.1.1 on 2024-09-03 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0006_boost_b_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task1.player'),
        ),
    ]
