# Generated by Django 5.1.1 on 2024-09-03 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelprize',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task2.player'),
        ),
        migrations.AlterField(
            model_name='levelprize',
            name='received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerlevel',
            name='completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
