# Generated by Django 5.1.1 on 2024-09-03 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0002_levelprize_received_by_alter_levelprize_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelprize',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task2.player'),
        ),
    ]
